[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "y0y0-v9696-virtu4l-p3t"
version = "0.1.0"
description = "Pacote Python do projeto y0y0"
readme = { text = "Pacote Python do projeto y0y0.", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "y0y09696n1c3h4ck3r" }
]
dependencies = []

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"y0y0.v9696.virtu4l" = ["*.png", "*.jpg","*.jpeg","*.gif"]
